"""
TERA PULSE - LiDAR Visualization Module
Member 3 - Computer Vision / Visualization

Responsibilities:
    1. Visualize LiDAR point clouds.
    2. Visualize semantic segmentation.
    3. Visualize the adaptive 2.5D grid generated by M4.
    4. Visualize elevation information.
    5. Generate a semantic navigation / traversability map.

IMPORTANT:
    This module does NOT generate the adaptive grid.
    Adaptive-grid generation belongs to Member 4.
"""

from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import open3d as o3d


# ======================================================================
# SEMANTIC LABELS
# ======================================================================

SEMANTIC_LABELS = {
    0: "Ground",
    1: "Static Obstacle",
    2: "Dynamic Object",
    3: "Unknown",
}


# RGB colors for semantic point-cloud visualization
SEMANTIC_COLORS = {
    0: [0.20, 0.80, 0.20],   # Ground - green
    1: [0.90, 0.20, 0.20],   # Static obstacle - red
    2: [0.20, 0.40, 1.00],   # Dynamic candidate - blue
    3: [0.60, 0.60, 0.60],   # Unknown - grey
}


# ======================================================================
# LOAD POINT CLOUD
# ======================================================================

def load_point_cloud(
    path: str | Path,
) -> o3d.geometry.PointCloud:
    """
    Load a PCD/PLY point cloud using Open3D.
    """

    path = str(path)

    pcd = o3d.io.read_point_cloud(path)

    if pcd.is_empty():
        raise ValueError(
            f"Point cloud is empty or could not be loaded: {path}"
        )

    return pcd


# ======================================================================
# HEIGHT COLORS
# ======================================================================

def height_colors(
    points: np.ndarray,
) -> np.ndarray:
    """
    Generate normalized colors based on point height.
    """

    points = np.asarray(points)

    if len(points) == 0:
        return np.empty((0, 3))

    z = points[:, 2]

    z_min = np.min(z)
    z_max = np.max(z)

    if z_max == z_min:
        normalized = np.zeros_like(z)
    else:
        normalized = (
            (z - z_min)
            / (z_max - z_min)
        )

    cmap = plt.get_cmap("viridis")

    return cmap(normalized)[:, :3]


# ======================================================================
# HEIGHT VISUALIZATION
# ======================================================================

def visualize_height(
    points: np.ndarray,
    window_name: str = "TERA PULSE - LiDAR Height",
) -> None:
    """
    Display LiDAR points colored according to elevation.
    """

    points = np.asarray(points)

    if len(points) == 0:
        print("No points available for height visualization.")
        return

    pcd = o3d.geometry.PointCloud()

    pcd.points = (
        o3d.utility.Vector3dVector(points)
    )

    pcd.colors = (
        o3d.utility.Vector3dVector(
            height_colors(points)
        )
    )

    o3d.visualization.draw_geometries(
        [pcd],
        window_name=window_name,
    )


# ======================================================================
# SEMANTIC COLORS
# ======================================================================

def semantic_colors(
    labels: np.ndarray,
) -> np.ndarray:
    """
    Convert integer semantic labels to RGB colors.

    0 = Ground
    1 = Static obstacle
    2 = Dynamic object candidate
    3 = Unknown
    """

    labels = np.asarray(labels)

    colors = np.zeros(
        (len(labels), 3),
        dtype=float,
    )

    for label, color in SEMANTIC_COLORS.items():
        colors[labels == label] = color

    return colors


# ======================================================================
# SEMANTIC 3D VISUALIZATION
# ======================================================================

def visualize_semantic(
    points: np.ndarray,
    labels: np.ndarray,
    window_name: str = "TERA PULSE - 3D Semantic LiDAR",
) -> None:
    """
    Display semantic LiDAR classification.

    Green  -> Ground
    Red    -> Static obstacle
    Blue   -> Dynamic-object candidate
    Grey   -> Unknown
    """

    points = np.asarray(points)
    labels = np.asarray(labels)

    if len(points) != len(labels):
        raise ValueError(
            "Points and labels must have the same length."
        )

    if len(points) == 0:
        print("No points available for semantic visualization.")
        return

    pcd = o3d.geometry.PointCloud()

    pcd.points = (
        o3d.utility.Vector3dVector(points)
    )

    pcd.colors = (
        o3d.utility.Vector3dVector(
            semantic_colors(labels)
        )
    )

    o3d.visualization.draw_geometries(
        [pcd],
        window_name=window_name,
    )


# ======================================================================
# TOP-DOWN VISUALIZATION
# ======================================================================

def plot_top_down(
    points: np.ndarray,
    labels: np.ndarray | None = None,
    title: str = "TERA PULSE - Semantic Top-Down View",
    save_path: str | Path | None = None,
) -> None:
    """
    Create a top-down X-Y view of the LiDAR point cloud.
    """

    points = np.asarray(points)

    if len(points) == 0:
        print("No points available for top-down visualization.")
        return

    plt.figure(
        figsize=(10, 8)
    )

    if labels is None:

        plt.scatter(
            points[:, 0],
            points[:, 1],
            s=1,
        )

    else:

        colors = semantic_colors(
            np.asarray(labels)
        )

        plt.scatter(
            points[:, 0],
            points[:, 1],
            s=1,
            c=colors,
        )

    plt.scatter(
        [0],
        [0],
        marker="^",
        s=100,
        color="black",
        label="LiDAR sensor",
    )

    plt.xlabel("X (m)")
    plt.ylabel("Y (m)")
    plt.title(title)
    plt.axis("equal")
    plt.legend()
    plt.tight_layout()

    if save_path is not None:

        plt.savefig(
            save_path,
            dpi=200,
            bbox_inches="tight",
        )

        print(
            f"Saved top-down visualization -> {save_path}"
        )

    plt.show()


# ======================================================================
# ADAPTIVE GRID VISUALIZATION
# ======================================================================

def plot_adaptive_grid(
    cells,
    title: str = "TERA PULSE - Adaptive Grid Map",
    save_path: str | Path | None = None,
) -> None:
    """
    Visualize the adaptive cells generated by M4.

    IMPORTANT:
        This function ONLY visualizes cells.

        It does NOT:
            - calculate distance
            - select resolution
            - create cells
            - perform aggregation

        Those operations belong to M4.
    """

    cells = list(cells)

    if not cells:
        print("No adaptive-grid cells available.")
        return

    fig, ax = plt.subplots(
        figsize=(11, 8)
    )

    resolutions = sorted(
        set(
            float(cell.resolution)
            for cell in cells
        )
    )

    cmap = plt.get_cmap("viridis")

    if len(resolutions) == 1:

        normalized = {
            resolutions[0]: 0.5
        }

    else:

        normalized = {
            resolution:
                index / (len(resolutions) - 1)
            for index, resolution
            in enumerate(resolutions)
        }

    for cell in cells:

        resolution = float(
            cell.resolution
        )

        rect = plt.Rectangle(
            (
                cell.x - resolution / 2,
                cell.y - resolution / 2,
            ),
            resolution,
            resolution,
            facecolor=cmap(
                normalized[resolution]
            ),
            edgecolor="black",
            linewidth=0.15,
            alpha=0.75,
        )

        ax.add_patch(rect)

    ax.scatter(
        [0],
        [0],
        marker="^",
        s=120,
        color="black",
        label="LiDAR sensor",
        zorder=5,
    )

    ax.set_xlabel("X (m)")
    ax.set_ylabel("Y (m)")
    ax.set_title(title)
    ax.set_aspect("equal")
    ax.legend()

    plt.tight_layout()

    if save_path is not None:

        plt.savefig(
            save_path,
            dpi=200,
            bbox_inches="tight",
        )

        print(
            f"Saved adaptive-grid visualization -> {save_path}"
        )

    plt.show()


# ======================================================================
# 2.5D ELEVATION MAP
# ======================================================================

def plot_25d_elevation(
    cells,
    title: str = "TERA PULSE - 2.5D Elevation Map",
    save_path: str | Path | None = None,
) -> None:
    """
    Visualize elevation stored inside M4 adaptive cells.

    Cell size is retained in the marker size.
    Color represents elevation.
    """

    cells = list(cells)

    if not cells:
        print("No cells available for elevation visualization.")
        return

    x = np.array(
        [cell.x for cell in cells]
    )

    y = np.array(
        [cell.y for cell in cells]
    )

    z = np.array(
        [cell.elevation for cell in cells]
    )

    resolution = np.array(
        [
            cell.resolution
            for cell in cells
        ]
    )

    plt.figure(
        figsize=(11, 8)
    )

    scatter = plt.scatter(
        x,
        y,
        c=z,
        s=resolution * 20,
        cmap="viridis",
    )

    plt.colorbar(
        scatter,
        label="Elevation (m)",
    )

    plt.scatter(
        [0],
        [0],
        marker="^",
        s=100,
        color="black",
        label="LiDAR sensor",
    )

    plt.xlabel("X (m)")
    plt.ylabel("Y (m)")
    plt.title(title)
    plt.axis("equal")
    plt.legend()
    plt.tight_layout()

    if save_path is not None:

        plt.savefig(
            save_path,
            dpi=200,
            bbox_inches="tight",
        )

        print(
            f"Saved 2.5D elevation map -> {save_path}"
        )

    plt.show()


# ======================================================================
# NAVIGATION / TRAVERSABILITY MAP
# ======================================================================

def plot_navigation_map(
    cells,
    title: str = (
        "TERA PULSE - "
        "Navigation / Traversability Map"
    ),
    save_path: str | Path | None = None,
) -> None:
    """
    Visualize semantic information stored in M4 cells.

    Color meaning:

        GREEN -> Ground / potentially traversable
        RED   -> Static obstacle
        BLUE  -> Dynamic-object candidate
        GREY  -> Unknown

    IMPORTANT:
        This is NOT path planning.

        It creates a semantic map that can be supplied
        to a downstream navigation/path-planning module.
    """

    cells = list(cells)

    if not cells:
        print(
            "No cells available for navigation visualization."
        )
        return

    semantic_colors_map = {

        "ground": "green",

        "static_obstacle": "red",

        "dynamic_object": "blue",

        "unknown": "gray",

        # Compatibility with possible labels
        "vehicle": "blue",

        "vegetation": "red",
    }

    fig, ax = plt.subplots(
        figsize=(11, 8)
    )

    present_classes = set()

    for cell in cells:

        semantic_class = str(
            cell.semantic_class
        ).lower()

        color = semantic_colors_map.get(
            semantic_class,
            "gray",
        )

        present_classes.add(
            semantic_class
        )

        resolution = float(
            cell.resolution
        )

        rect = plt.Rectangle(
            (
                cell.x - resolution / 2,
                cell.y - resolution / 2,
            ),
            resolution,
            resolution,
            facecolor=color,
            edgecolor="black",
            linewidth=0.15,
            alpha=0.75,
        )

        ax.add_patch(rect)

    # --------------------------------------------------------------
    # Sensor
    # --------------------------------------------------------------

    ax.scatter(
        [0],
        [0],
        marker="^",
        s=120,
        color="black",
        zorder=5,
        label="LiDAR sensor",
    )

    # --------------------------------------------------------------
    # Legend
    # --------------------------------------------------------------

    legend_items = [
        (
            "ground",
            "green",
            "Ground / potentially traversable",
        ),
        (
            "static_obstacle",
            "red",
            "Static obstacle",
        ),
        (
            "dynamic_object",
            "blue",
            "Dynamic-object candidate",
        ),
        (
            "unknown",
            "gray",
            "Unknown",
        ),
    ]

    handles = []

    for (
        key,
        color,
        label,
    ) in legend_items:

        if (
            key in present_classes
            or key == "ground"
        ):

            handles.append(
                plt.Rectangle(
                    (0, 0),
                    1,
                    1,
                    facecolor=color,
                    edgecolor="black",
                    label=label,
                )
            )

    handles.append(
        plt.Line2D(
            [0],
            [0],
            marker="^",
            color="black",
            linestyle="None",
            markersize=9,
            label="LiDAR sensor",
        )
    )

    ax.legend(
        handles=handles,
        loc="upper right",
    )

    ax.set_xlabel("X (m)")
    ax.set_ylabel("Y (m)")
    ax.set_title(title)
    ax.set_aspect("equal")

    plt.tight_layout()

    if save_path is not None:

        plt.savefig(
            save_path,
            dpi=200,
            bbox_inches="tight",
        )

        print(
            f"Saved navigation map -> {save_path}"
        )

    plt.show()


# ======================================================================
# VISUALIZATION SUMMARY
# ======================================================================

def print_visualization_summary(
    points: np.ndarray,
    labels: np.ndarray | None = None,
    cells=None,
) -> None:
    """
    Print a compact summary for demo/presentation.
    """

    points = np.asarray(points)

    print(
        "\n===== VISUALIZATION SUMMARY ====="
    )

    print(
        f"Point count: {len(points)}"
    )

    if labels is not None:

        labels = np.asarray(labels)

        print(
            "\nSemantic classes:"
        )

        for label, name in SEMANTIC_LABELS.items():

            count = int(
                np.sum(
                    labels == label
                )
            )

            print(
                f"  {name}: {count}"
            )

    if cells is not None:

        cells = list(cells)

        print(
            f"\nAdaptive grid cells: "
            f"{len(cells)}"
        )

        resolutions = sorted(
            set(
                float(cell.resolution)
                for cell in cells
            )
        )

        print(
            "Resolutions: "
            + ", ".join(
                f"{r:g} m"
                for r in resolutions
            )
        )


# ======================================================================
# BASIC MANUAL TEST
# ======================================================================

if __name__ == "__main__":

    print(
        "TERA PULSE - M3 Visualization Module"
    )

    pcd_path = Path(
        "data/lidar/0001.pcd"
    )

    if not pcd_path.exists():

        print(
            f"Test file not found: {pcd_path}"
        )

        print(
            "Run this module from the project root."
        )

    else:

        pcd = load_point_cloud(
            pcd_path
        )

        points = np.asarray(
            pcd.points
        )

        print(
            f"Loaded {len(points)} LiDAR points."
        )

        visualize_height(
            points
        )